<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<?php if($this->get_description()) : ?>
<meta name="Description" content="<?php echo $this->get_description(); ?>" />
<?php endif; ?>
<?php if($this->get_keywords()) : ?>
<meta name="Keywords" content="<?=$this->get_keywords()?>" />
<?php endif; ?>
<title><?=$this->get_title()?></title>
<link rel="stylesheet" rev="stylesheet" href="<?=$this->build_css_url()?>" type="text/css" />
<link rel="shortcut icon" href="<?=UrlBuilder::build_static('images/icon.png')?>" />
</head>
<body>222

                    <?php
                    $this->build_content();
                    ?>

  
<?php foreach($this->get_static_js_list() as $js):?>
<script type="text/javascript" src="<?=UrlBuilder::build_static($js); ?>"></script>
<?php endforeach;?>
<script type="text/javascript" src="<?=$this->build_js_url()?>"></script>
<?php $this->write_script_blocks(); ?>
</body>
</html>